%% caculate all vertexes' position including latent & observable (31 node)
%
%  call function: NULL
%
%  Function: This .m file is used for caculating All vertex's location for training images by using a fixed structure  LTM(generated by geodesic distance)
%
%  Input:  @curImgIndex: current image set index
%             @labels: All images labels - 16 points position
%             @LTM : LTM model
%             @imageNames£ºall image name
%
%  Output: @allVertexpos£ºcurrent image set's all vertex position
%
%  written by Sophia
%  last modified date : 2016.01.12
%%

function [allVertexpos] = caculateAllVertexes(curimgIndex,labels,imageNames,LTM)

vertexNum = 31;
imageNum = size(curimgIndex,1);        %image num
allVertexpos = zeros(imageNum,vertexNum*3);  %save all vertexes' position,e.g.[(x,y,z),(x,y,z),...,]
latTree = zeros(size(LTM,1),16);       %every LTM vertex(observable & latent) include the observable vertexes£¨0-include£¬1-not include)

%building a 0-1 matrix of LTM to caculate all vertex position ( including latent vertex£©
for i=1:size(LTM,1);
    latTree(i,uint16(LTM{i,1}(5:end))) = 1;
end
avg =  repmat(sum(latTree'),imageNum,1); % the numeber of  labels in each vertex of LTM

%caculate all vertex position(x,y,z)
allVertexpos(:,1:3:vertexNum*3) = (labels(curimgIndex,1:3:end)*latTree')./avg;  % x
allVertexpos(:,2:3:vertexNum*3) = (labels(curimgIndex,2:3:end)*latTree')./avg;  % y
allVertexpos(:,3:3:vertexNum*3) = (labels(curimgIndex,3:3:end)*latTree')./avg;  % z

%%modify the first vertex P0 into center of mass of hand. 
for t = 1:size(imageNames,1)
    I = imread(['./Training/Depth/',imageNames{t,1}]);
    threhold = max(I(find(I < 30000)));  %pre-process to get the hand
    [row,col] = find(I < 30000);
    I(find(I >= 30000)) = threhold;
    allVertexpos(t,1) = mean(col);
    allVertexpos(t,2) = mean(row);
    allVertexpos(t,3) = I(uint16(mean(row)),uint16(mean(col)));
end

% 
% %%test
% for i = 1:10%size(currIndex,1)
%     I = imread(['./Training/Depth/' imageNames{i,1}]);
%     figure;
%     imshow(I);
%     hold on;
%     x = sum(labels(i,1:3:end))/16;
%     y = sum(labels(i,2:3:end))/16;
%     %z = sum(labels(1,3:3:end))/16;
%     plot(x,y,'ro');
%     hold on;
%     x1 = allVertexpos(i,1);
%     y1 = allVertexpos(i,2);
%     %x1 = vertex(1,1);
%     plot(x1,y1,'g.');
% end

end

